### ISSUE TITLE
why pull-request merge --no-ff?

### ISSUE THREAD

**Issue by tmilos** [gushphp/gush#372] opened 2014-12-19 23:25 UTC
I'm calling for a discussion if anybody is willing to participate. There are couple of things I'm interested on, that depending on the approach could be related. 

## 1. no-ff vs ff
I'm not quite sure what's the point of merge --no-ff when log is cleaner when done with fast forward. Does anybody has an argument why should we have 2 times more commits in log with every second being a merge commit?

## 2. Tests failing after rebasing PR
Theoretically, a PR that has pass a CI build, could fail when rebased on ```master``` and merged. It worked on one base, but now on other it might not, depending on changes merged in the meanwhile. This might go well in hand with 1. above, so, if a PR is rebased on top of master, a new PR can be made, CI build waited to finish, and if it's a pass then master fast forwarded to it - resulting in tests being run after rebase, as well as not making an annoying merge commit. 

## 3. Who will wait for so many CI builds?
When you approach to PR reviewing and merging, you usually have more then one in queue. So, maybe it would be a good idea, to rebase them all onto some temporary ```merge``` branch, one onto other, then, when done, commit a transaction, so to say, by making a new PR out of that ```merge``` branch, wait for CI build to finish on it, and then just fast forward ```master``` to that PR made out of ```merge``` branch. Ofc, if it fails due to some of them, you might not know for sure which one did it, but it's again better that happens on a PR before merge, rather then on ```master``` already being merged. 

Any comments?

**Comment by cordoval** [comment] 2015-01-11 21:27
any more on this to be added @tmilos @sstok

**Comment by tmilos** [comment] 2015-01-12 12:46
nope

**Comment by cordoval** [comment] 2015-02-11 00:49
i need to revive this @sstok @tmilos i think @tmilos is right

**Comment by cordoval** [comment] 2015-02-11 00:50
So let me explain, I have several branch features that run long on my repo project, whenever i launch a PR to be merged on that branch i use the base: option on .gush.yml. The problem is most of the changes are quick and need to be streamlined without a merge commit so in this case I agree with @tmilos :older_man:  :+1:

**Comment by sstok** [comment] 2015-02-11 09:44
OK, the only question is should we extend the pull-request:merge command or add a new branch:merge command with `--pr nn` as option for merging pull-requests?

**Comment by cordoval** [comment] 2015-04-13 04:10
this should be good to do as well to help @tmilos

**Comment by sstok** [comment] 2015-05-05 14:04
Should be simple enough. I will work on this one tomorrow.

**Comment by cordoval** [comment] 2015-05-09 02:09
@tmilos done, thanks for your patience :older_man: 

thanks @sstok

**Closed by cordoval** 2015-05-09 02:09 UTC
Labels: Feature, Has PR, High priority, idea
